project_id = "dxsomoutvqqkotadivki"

[functions.analyze-waste]
verify_jwt = false

[functions.notify-pending-mtrs]
verify_jwt = false

[functions.update-tracking-status]
verify_jwt = false

[functions.test-sinir-connection]
verify_jwt = false

[functions.sync-sinir]
verify_jwt = false

[functions.sinir-api]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
